version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "cubedsquare0"
    assignees:
      - "cubedsquare0"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"